create table Sensor
(
    id   int primary key generated by default as identity,
    name varchar(100) not null unique
);

create table Measurement
(
    id    int primary key generated by default as identity,
    value double precision check ( value > -101 ) check ( value < 101 ) not null ,
    raining boolean not null ,
    time_of_creation timestamp not null ,
    sensor varchar(100) references Sensor(name)on delete set null
);

